### ISSUE TITLE
L 5.2 error

### ISSUE THREAD

**Issue by simonfunk** [hakanersu/L5whmcs#3]
Hi, i get an error after updating to L 5.2

local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Foundation\Application::bindShared()' in D:\Workplace\Code\keevo\vendor\xuma\l5whmcs\src\Xuma\Whmcs\WhmcsServiceProvider.php:45

Simply change bindShare to singelton will fix it ;)

**Comment by hakanersu** [comment]
Thank you for your report @simonfunk ill check as soon as possible.

**Comment by hakanersu** [comment]
Fixed.
